# Настройка логгера
logger:
  # тип логгера Debug|Info|Error|Off
  # понижение логгера от Off к Debug замедляет программу
  type: "Debug"
  # путь к сохранению логов
  path: "logs/app.log"
# Настройка Симуляции
simulation:
  # тип симуляции Train|Experiment
  type: "Experiment"
  # Если тип симуляции Train: до какого возраста обучать
  targetAge: 100
  # Если тип симуляции Train: колличество лучших в эпохе
  endCountAgent: 8
  # стартовое колличество агентов одной стратегии(Sing)
  startCountAgent: 20
  # Если тип симуляции Experiment: 
  # максимальный срок проведения эксперимента
  # -1 в значении - нет ограничений
  maxAgeExperiment: -1
  # адрес загрузки одной стратегии для обучения(Train)
  pathLoadSing: "loads/sing.json"
  # адрес загрузки нескольких стратегий для эксперимента(Experiment)
  pathLoadSings: "loads/sings.json"
  # адреса выгрузки лучшей стратегии и статистики после обучения(Train) 
  pathSaveSing: "saves/best-Sing.json"
  pathSaveStat: "saves/stat-train.csv"
  # Настройка мира
  world:
    # линейные размеры мира
    x_size: 20
    y_size: 20
    # стартовое и максимальное значение яда в каждой клетке
    startPoisonLevel: 10
    maxPoisonLevel: 120
    # шанс появление еды в клетке от 0 до 10
    chanceToNewFood: 50