# Настройка конфига
logger:
  # тип логгера Debug|Info|Error|Off
  type: "Debug"
  # путь к сохранению логов
  path: "logs/app.log"
# Настройка Симуляции
simulation:
  # тип симуляции Train|Experiment
  type: "Experiment"
  # до какого возраста обучать
  targetAge: 100
  # колличество агентов для обучения
  startCountAgent: 20
  # колличество лучших в эпохе
  endCountAgent: 8
  # максимальный срок проведения эксперимента
  # -1 в значении - нет ограничений
  maxAgeExperiment: -1
  # пути сохранения данных
  pathLoadSing: "loads/sing.json"
  pathLoadSings: "loads/sings.json"
  pathSaveSing: "saves/best-Sing.json"
  pathSaveStat: "saves/stat-train.csv"
